### ISSUE TITLE
Update configuration example in README.md, and update main.py

### ISSUE THREAD

**Issue by Brutalbeard** [Brutalbeard/ghas-policy-as-code#1]
Configuration file should look like the following 

```yaml
secret-scanning:
  low: 30
  medium: 15
  high: 7
  critical: 3
```

This is just an example, the user will set the values on their own
